name: matrix_digital_rain_effect
description: Flutter Matrix Digital Rain is a mesmerizing visual display inspired by the iconic Matrix movie. This Flutter-based project creates a simulation of the cascading green characters seen in the film, with the added feature of user interactivity. Users can tap on the screen to generate a burst of digital rain, or swipe to change the direction of the falling characters. The project utilizes GraphX's optimized rendering engine to ensure smooth performance even on low-end devices. With its sleek design and intuitive user experience, Flutter Matrix Digital Rain is sure to delight both fans of the Matrix and tech enthusiasts alike.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter_web: ^0.2.2
  graphx: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-VariableFont_wght.ttf